# Generated by Django 3.1 on 2020-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='qty_in_stock',
            field=models.PositiveIntegerField(verbose_name='Quantity Available'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='period',
            field=models.DateField(auto_now_add=True),
        ),
    ]
