# Generated by Django 3.1 on 2020-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20200908_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='qty_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Available'),
        ),
    ]
